spring:
  application:
    name: itcast-tanhua-sso
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.47:3306/mytanhua?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: mypassword
  redis:
    jedis:
      pool:
        max-wait: 5000ms
        max-idle: 100
        min-idle: 10
    timeout: 10s
    cluster:
      nodes: 192.168.1.47:6379,192.168.1.47:6380,192.168.1.47:6381
      max-redirects: 5
server:
  port: 18080
mybatis-plus:
  type-enums-package: com.tanhua.sso.enums
  global-config:
    db-config:
      table-prefix: tb_
      id-type: auto
rocketmq:
  name-server: 192.168.1.47:9876
  producer:
    group: tanhua
jwt:
  secret: 76bd425b6f29f7fcc2e0bfc286043df1

aliyun:
  sms:
    regionId: cn-hangzhou
    accessKeyId: LTAI4G7d2Q9CHc741gighjTF
    accessKeySecret: uKOOGdIKvmoGhHlej8cJY8H3nlU6Fj
    domain: dysmsapi.aliyuncs.com
    signName: ABC商城
    templateCode: SMS_204756062